name: Check Code Formatting 🛠️
on:
  workflow_call:
jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: clang-format check 🐉
        id: clang-format
        uses: ./.github/actions/run-clang-format
        with:
          failCondition: error

  cmake-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cmake-format check 🎛️
        id: cmake-format
        uses: ./.github/actions/run-cmake-format
        with:
          failCondition: error

  cargo-fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: rustfmt
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: deps/c-webvtt-in-video-stream/Cargo.toml
